# Generated by Django 5.2.8 on 2026-07-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userstreak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(choices=[('kaa', 'Qaraqalpaqsha'), ('en', 'English'), ('ru', 'Russian'), ('uz', 'Uzbek')], default='en', max_length=3, verbose_name='Preferred Language'),
        ),
    ]
