# Generated by Django 5.2.8 on 2026-07-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_customuser_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='completed_quizzes',
            field=models.JSONField(default=list, help_text='List of completed quiz IDs'),
        ),
    ]
