# Generated by Django 5.2.8 on 2026-07-02 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprogress_completed_quizzes'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='energy',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=6, verbose_name='Energy'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_annual',
            field=models.BooleanField(default=False, verbose_name='Is Annual'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_bonus_claimed',
            field=models.DateField(blank=True, null=True, verbose_name='Last Daily Bonus Claimed'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='redeemed_xp',
            field=models.PositiveIntegerField(default=0, verbose_name='Redeemed XP'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_type',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('ultra', 'Ultra')], default='free', max_length=10, verbose_name='Subscription Type'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
    ]
