# Generated by Django 5.2.8 on 2026-07-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_course_creator_customuser_energy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bonus_xp',
            field=models.PositiveIntegerField(default=0, verbose_name='Bonus XP'),
        ),
    ]
