"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-krv#ae$oed5229%c5ttb(dwn#2%g16!sap$*u+x2vgeojkgnik')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', # Added for i18n
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.UserLanguageMiddleware',
    'core.middleware.StreakMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n', # Added for i18n
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
CSRF_TRUSTED_ORIGINS = [
    'https://study.pythonanywhere.com/',
]
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv('DB_NAME', 'study_db'),
#         'USER': os.getenv('DB_USER', 'azmtx'),
#         'PASSWORD': os.getenv('DB_PASSWORD', 'Azamat0603'),
#         'HOST': os.getenv('DB_HOST', 'db'),
#         'PORT': os.getenv('DB_PORT', '5432'),
#         # Gevent-friendly settings
#         'CONN_MAX_AGE': 0,  # Don't persist connections (important for gevent)
#         'ATOMIC_REQUESTS': False,  # Disable automatic transactions
#         'OPTIONS': {
#             'connect_timeout': 10,
#         }
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True # Explicitly set

USE_TZ = True

from django.utils.translation import gettext_lazy as _

LANGUAGES = [
    ('en', _('English')),
    ('ru', _('Russian')),
    ('kaa', _('Qaraqalpaqsha')),
    ('uz', _('Uzbek')),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'core.CustomUser'

# Authentication URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/chatbot/'
LOGOUT_REDIRECT_URL = '/'

# Gemini API Key (loaded from .env file)
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')

# ============================================================================
# CELERY CONFIGURATION (Optional - only for VPS deployments with Redis)
# ============================================================================
# Set USE_CELERY=True in .env to enable Celery (requires Redis)
USE_CELERY = os.getenv('USE_CELERY', 'False') == 'True'

if USE_CELERY:
    # Celery Broker (Redis)
    CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://redis:6379/0')

    # Celery Result Backend (Redis)
    CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://redis:6379/0')

    # Celery accepts JSON serialization only (more secure)
    CELERY_ACCEPT_CONTENT = ['json']
    CELERY_TASK_SERIALIZER = 'json'
    CELERY_RESULT_SERIALIZER = 'json'

    # Timezone configuration
    CELERY_TIMEZONE = 'UTC'
    CELERY_ENABLE_UTC = True

    # Task result expiration (1 hour)
    CELERY_RESULT_EXPIRES = 3600

    # Task routing - route heavy tasks to separate queue
    CELERY_TASK_ROUTES = {
        'core.tasks.generate_course_task': {
            'queue': 'heavy_tasks',
            'routing_key': 'heavy_tasks',
        },
        # All other tasks go to default queue (including chatbot)
        'core.tasks.chatbot_response_task': {
            'queue': 'default',
            'routing_key': 'default',
        },
    }

    # Default queue configuration
    CELERY_TASK_DEFAULT_QUEUE = 'default'
    CELERY_TASK_DEFAULT_EXCHANGE = 'default'
    CELERY_TASK_DEFAULT_ROUTING_KEY = 'default'

    # Task execution settings
    CELERY_TASK_ACKS_LATE = True  # Acknowledge task after execution
    CELERY_WORKER_PREFETCH_MULTIPLIER = 4  # Prefetch 4 tasks per worker (CRITICAL for parallel execution)
    CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000  # Restart worker after 1000 tasks

    # Task time limits (in seconds)
    CELERY_TASK_SOFT_TIME_LIMIT = 300  # 5 minutes soft limit
    CELERY_TASK_TIME_LIMIT = 360  # 6 minutes hard limit

    # Retry configuration
    CELERY_TASK_RETRY_BACKOFF = True
    CELERY_TASK_RETRY_BACKOFF_MAX = 600  # Max 10 minutes between retries
    CELERY_TASK_RETRY_JITTER = True  # Add randomness to retry delays

    # Worker pool configuration (Gevent for non-blocking I/O)
    # This is set via command line: --pool=gevent --concurrency=N
    # But we can set defaults here
    CELERY_WORKER_POOL = 'gevent'
    CELERY_WORKER_CONCURRENCY = 100  # Default for chat workers

    # Gevent-specific settings for database connections
    # Close database connections after each task to prevent blocking
    CELERY_WORKER_SEND_TASK_EVENTS = True
    CELERY_TASK_SEND_SENT_EVENT = True

    # Logging
    CELERY_WORKER_LOG_FORMAT = '[%(asctime)s: %(levelname)s/%(processName)s] %(message)s'
    CELERY_WORKER_TASK_LOG_FORMAT = '[%(asctime)s: %(levelname)s/%(processName)s][%(task_name)s(%(task_id)s)] %(message)s'

    # Beat scheduler (if needed for periodic tasks in the future)
    CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
